FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv

# Set working directory to homework (optional)
WORKDIR /app

COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

COPY homework/mean_predict.py .

ENTRYPOINT [ "python", "mean_predict.py" ]