FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip
RUN pip install pipenv

# Set working directory inside the container
WORKDIR /app

# Install Python dependencies
COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

# Copy your script and model from the local 'homework' folder into the container
COPY homework/mean_predict.py .
COPY homework/model.bin .

# Set the entrypoint for the container
ENTRYPOINT [ "python", "mean_predict.py" ]
